# Generated by Django 3.2.8 on 2021-10-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='input_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_grade', models.CharField(max_length=50)),
                ('sys_pressure', models.IntegerField()),
                ('specified_od', models.FloatField()),
                ('minimum_wall_thickness', models.FloatField()),
                ('tube_age', models.IntegerField()),
                ('measured_oxide_thickness', models.FloatField()),
                ('lmp_curve', models.CharField(max_length=50)),
                ('thickest_wall', models.IntegerField()),
                ('thinnest_wall', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
