# Generated by Django 3.2.8 on 2021-10-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20211029_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input_data',
            name='lmp_curve',
        ),
        migrations.RemoveField(
            model_name='input_data',
            name='material_grade',
        ),
        migrations.RemoveField(
            model_name='input_data',
            name='measured_oxide_thickness',
        ),
        migrations.RemoveField(
            model_name='input_data',
            name='minimum_wall_thickness',
        ),
        migrations.RemoveField(
            model_name='input_data',
            name='thickest_wall',
        ),
        migrations.RemoveField(
            model_name='input_data',
            name='thinnest_wall',
        ),
        migrations.RemoveField(
            model_name='input_data',
            name='tube_age',
        ),
    ]
