# Generated by Django 3.2.8 on 2021-10-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20211029_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input_data',
            old_name='specified_od',
            new_name='od',
        ),
        migrations.RenameField(
            model_name='input_data',
            old_name='sys_pressure',
            new_name='pressure',
        ),
    ]
