# Generated by Django 3.2.8 on 2021-10-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20211029_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='input_data',
            name='measured_oxide_thickness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='input_data',
            name='min_wall_thickness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='input_data',
            name='thickest_wall',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='input_data',
            name='thinnest_wall',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='input_data',
            name='tube_age',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='input_data',
            name='pressure',
            field=models.FloatField(),
        ),
    ]
