# Generated by Django 3.2.8 on 2021-11-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20211029_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='input_data',
            name='material',
            field=models.CharField(default='T22 2.25Cr-1Mo', max_length=50),
        ),
        migrations.AlterField(
            model_name='input_data',
            name='measured_oxide_thickness',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='input_data',
            name='min_wall_thickness',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='input_data',
            name='thickest_wall',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='input_data',
            name='thinnest_wall',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='input_data',
            name='tube_age',
            field=models.FloatField(),
        ),
    ]
