# Generated by Django 3.2.8 on 2021-11-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_alter_input_data_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_data',
            name='material',
            field=models.CharField(choices=[('T22 2.25Cr-1Mo', 'T22 2.25Cr-1Mo'), ('Carbon Steel', 'Carbon Steel'), ('TP347H', 'TP347H'), ('T1 Cr-Mo', 'T1 Cr-Mo'), ('T2 0.5Cr-0.5Mo', 'T2 0.5Cr-0.5Mo'), ('T12 1Cr-0.5Mo', 'T12 1Cr-0.5Mo'), ('T11 1.25Cr-0.5Mo', 'T11 1.25Cr-0.5Mo'), ('TP 321H', 'TP 321H'), ('TP 316H', 'TP 316H'), ('TP 304H', 'TP 304H'), ('T91 Cr-Mo-V', 'T91 Cr-Mo-V'), ('T5 5Cr-0.5Mo', 'T5 5Cr-0.5Mo')], default='T22 2.25Cr-1Mo', max_length=50),
        ),
    ]
