# Generated by Django 4.0b1 on 2021-11-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_input_data_oxide_method_alter_input_data_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='input_data',
            name='stress_curve',
            field=models.CharField(default='Average', max_length=20),
        ),
        migrations.AlterField(
            model_name='input_data',
            name='oxide_method',
            field=models.CharField(default='equation', max_length=20),
        ),
    ]
