# Generated by Django 4.0b1 on 2021-11-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_input_data_stress_curve_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rate_input_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
            ],
        ),
    ]
