# Generated by Django 4.0b1 on 2021-11-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_rate_input_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate_input_data',
            old_name='rate',
            new_name='oxide_growth_rate',
        ),
    ]
