# Generated by Django 4.0b1 on 2021-11-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0014_rate_input_data_estimated_operating_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate_input_data',
            name='estimated_operating_temperature',
        ),
    ]
