# Generated by Django 4.0b1 on 2021-11-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0016_eot_input_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eot_input_data',
        ),
        migrations.DeleteModel(
            name='rate_input_data',
        ),
        migrations.AddField(
            model_name='input_data',
            name='est_op_temp',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='input_data',
            name='oxide_growth_rate',
            field=models.FloatField(default=5),
        ),
    ]
