# Generated by Django 4.0b1 on 2021-11-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0017_delete_eot_input_data_delete_rate_input_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_data',
            name='est_op_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='input_data',
            name='oxide_growth_rate',
            field=models.FloatField(),
        ),
    ]
