# Generated by Django 3.2.9 on 2021-12-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0026_alter_input_data_est_op_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='input_data',
            name='key',
            field=models.FloatField(null=True),
        ),
    ]
